### ISSUE TITLE
Engine Binary Sensor Not working

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#12]
So, first time trying the integration on running car and the Engine Binary Sensor doesn't update, the engine is showing as true in the data though:

```
vehicleLocation:
coord:
lat: xxxxxx
lon: -xxxxxxx
alt: 0
type: 0
head: 167
speed:
value: 0
unit: 1
accuracy:
hdop: 10
pdop: 10
time: '20210412101103'
vehicleStatus:
airCtrlOn: true
engine: true
doorLock: true
doorOpen:
frontLeft: 0
frontRight: 0
backLeft: 0
backRight: 0
trunkOpen: false
airTemp:
value: 0CH
unit: 0
hvacTempType: 1
defrost: false
lowFuelLight: false
acc: true
hoodOpen: false
transCond: true
steerWheelHeat: 0
sideBackWindowHeat: 0
dte:
value: 88
unit: 3
tirePressureLamp:
tirePressureLampAll: 0
tirePressureLampFL: 0
tirePressureLampFR: 0
tirePressureLampRL: 0
tirePressureLampRR: 0
battery:
batSoc: 65
batState: 0
time: '20210412101103'
odometer:
value: 4175.7
unit: 1
```

**Comment by fuatakgun** [comment]
my bad, I had left a `!` mark inside the code mistakenly. will fix it today

**Comment by fuatakgun** [comment]
should be fixed here: https://github.com/fuatakgun/kia_uvo/commit/f8c1c6474ff8fdf61e372238ae5d450dfd1d36b9

**Comment by holdestmade** [comment]
Still doesn't see to work f8c1c64

line 27 of binary_sensor.py, is this the ! that should be removed ?

`    ("engine", "Engine", "!vehicleStatus.engine", "mdi:engine", "mdi:engine-off", DEVICE_CLASS_POWER),
`

**Comment by fuatakgun** [comment]
my bad, commit has been merged, you are good to take the latest version. and yes, it is about '!` in the beginning

**Comment by holdestmade** [comment]
Working great now thanks
