### ISSUE TITLE
Add On stopped working since today

### ISSUE THREAD

**Issue by LuckyTriple7** [fuatakgun/kia_uvo#280]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
Europe / Germany / KIA

**Describe the bug**
After Restart, all entities are unavailable.
Deleting the Integration and add it again does not fix the Issue.

**Debug logs if an error occurred**

Log after HA restart:
```
2022-02-07 09:18:47 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 427, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers
```

```
2022-02-07 09:18:47 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.de for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes

```

Log after deleting and add again:

`2022-02-07 10:12:13 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user
    self.token = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 101, in login
    self.device_id, self.stamp = self.get_device_id()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 175, in get_device_id
    device_id = response["resMsg"]["deviceId"]
TypeError: string indices must be integers
`

I also tried with a newly created car sharing account.

**Comment by LuckyTriple7** [comment]
Note: KIA Connect App is working fine for both Accounts.

**Comment by fuatakgun** [comment]
can you enable debug logging and share the logs following README?

**Comment by LuckyTriple7** [comment]
Hello,
here are the LOGS when i try to add the Integration:

```
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID request {'ccsp-service-id': 'fdc85c00-0a2f-4c64-bcb4-2cfb1500730a', 'Stamp': '9o3mpjuu/h4vH6cwbgTzPD70J+JaprZSWlyFNmfNg2qhql7gngJHgZp8DEweTNw=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.kia.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': 'dqsB--YjklQ:APA91bFvVGGTTWv8MA9ECMvBXlYjFUHqYbZOooEcyL6qf33iUWNiuzmBOOKFbfimbRgG07-pxoaRU-pe2CPy8ADyrTAjwrR7XamZj4twMH6xBtqnpfW9Xkw2Lo2hVrW3EoCIzVt3CqI4', 'pushType': 'GCM', 'uuid': 'faea324b-dbcf-4943-a33b-6808c597d16a'}
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID response {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 13028.180999994278', 'msgId': '8c415aad-bf93-414d-8409-d5896f0fc0f6'}
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Retry count 0 - Invalid stamp 9o3mpjuu/h4vH6cwbgTzPD70J+JaprZSWlyFNmfNg2qhql7gngJHgZp8DEweTNw=
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID request {'ccsp-service-id': 'fdc85c00-0a2f-4c64-bcb4-2cfb1500730a', 'Stamp': '9o3mpjuu/h4vH6cwbgTzPD70J+JaprZSWlyFNmfNg2qhql7gngJHgZp8DEsXT9w=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.kia.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': 'dqsB--YjklQ:APA91bFvVGGTTWv8MA9ECMvBXlYjFUHqYbZOooEcyL6qf33iUWNiuzmBOOKFbfimbRgG07-pxoaRU-pe2CPy8ADyrTAjwrR7XamZj4twMH6xBtqnpfW9Xkw2Lo2hVrW3EoCIzVt3CqI4', 'pushType': 'GCM', 'uuid': 'faea324b-dbcf-4943-a33b-6808c597d16a'}
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Get Device ID response {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 12718.362999916077', 'msgId': 'd01522d6-48df-4f0d-8181-cd9ca67df3cf'}
2022-02-07 10:41:24 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - Retry count 10 - Invalid stamp 9o3mpjuu/h4vH6cwbgTzPD70J+JaprZSWlyFNmfNg2qhql7gngJHgZp8DEsXT9w=
2022-02-07 10:41:24 ERROR (MainThread) [custom_components.kia_uvo.config_flow] kia_uvo Exception in kia_uvo login : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user
    self.token = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 101, in login
    self.device_id, self.stamp = self.get_device_id()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 175, in get_device_id
    device_id = response["resMsg"]["deviceId"]
TypeError: string indices must be integers
```

**Comment by LuckyTriple7** [comment]
Note: KIA UVO is deprecated . KIA switched the APP to KIA Connect.
[https://connect.kia.com/de](url)

**Comment by fuatakgun** [comment]
the only difference between different apps, are their identification numbers located here: https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiEU.py#L40

Apparently, because of deprecation, current values are not working anymore, I need find out new ID either through code or traffic, but this has to wait till evening.

**Comment by tobiasbrage** [comment]
Same issue here, stopped working as of today.
Hoping for a fix shortly.
You guys are doing a great job btw! 👍

**Comment by nilrog** [comment]
I can add a +1 to having this issue since this morning. I have a Hyundai EV, living in EU, and the Bluelink app works fine.

**Comment by Utopia69** [comment]
Same here, Hyundai Tucson PHEV in EU

**Comment by milkplus27** [comment]
Also stopped working for me today - Hyundai Kona EV in EEC. All entities now reporting as "unavailable". Bluelink app seems to be working fine.

Want to echo that, otherwise, this integration has been great. keep up the good work!

**Comment by PierreLevres** [comment]
> the only difference between different apps, are their identification numbers located here: https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiEU.py#L40
> 
> Apparently, because of deprecation, current values are not working anymore, I need find out new ID either through code or traffic, but this has to wait till evening.

There is a discussion about the same topic in the BlueLinky discord about this. https://discord.com/channels/652755205041029120/940144903441244210

Some cooperation maybe?

**Comment by fuatakgun** [comment]
thanks, I had just arrived

**Comment by Tailor4** [comment]
one more affected. Using KIA

**Comment by fuatakgun** [comment]
that would be a perfect contribution, by the way, the problem should be resolved now, as new stamps are generated and released here 10 minutes ago: https://github.com/neoPix/bluelinky-stamps

**Comment by Growiel** [comment]
What does one needs to do to update this ? My logs still show "invalid stamps".

I updated the integration in HACS.

**Comment by JensKillermann** [comment]
Version 1.4.6 works with my hyundai kona eu (germany)!

**Comment by fuatakgun** [comment]
Same here, I confirm 1.4.6 works fine, please retest and comment here if you have any issues

**Comment by fuatakgun** [comment]
> What does one needs to do to update this ? My logs still show "invalid stamps".
> 
> I updated the integration in HACS.

1.4.6 released just now, try again

**Comment by tobiasbrage** [comment]
Updated and restarted. Not working.
Hyundai EU.

**Comment by LuckyTriple7** [comment]
Thx for fix that issue so fast 👍 working for me

**Comment by tobiasbrage** [comment]
Works great now after the last update.

**Comment by Utopia69** [comment]
1.4.6 works for me, Hyundai Tucson PHEV EU

**Comment by lavsejsIDBS** [comment]
1.4.6 Didn't work at first even after a couple of restarts. After enabling debugging it started working wit no errors seen in the logs.

**Comment by phantomsphorever** [comment]
I can't get 1.4.6. to work :-(
How do you "enable debugging" ?
Can you please elaborate?

**Comment by fuatakgun** [comment]
You can follow readme file to enable debug logs.

**Comment by lavsejsIDBS** [comment]
@phantomsphorever I don't think debugging made any difference, a couple of restarts and a bit of time fixed it after the update. It may have been a caching issue.

**Comment by phantomsphorever** [comment]
Thanks for the quick responses.
I removed the Integration and added it again - back to normal now !

**Comment by woody55uk** [comment]
I confirm that the 1.4.8 is now working for me (Kona EV in UK) with just an update in HACS and a restart. Thanks for everyone's work on this.

**Comment by fuatakgun** [comment]
Do not worry, it will be broken in next couple of hours :-) i am working on a fix
